### ISSUE TITLE
OTP intruptes Closed

### ISSUE THREAD

**Issue by subinesh21** [Vikash-3000/SOS-Safety-App#5]
I recieved a pop up in otp page that says...WE BLOCK THIS DEVICE FOR UNUSUAL ACTIVITIES ...why ??

**Comment by Vikash-3000** [comment]
Ok will see and i will fix it

**Comment by Vikash-3000** [comment]
I have used firebase otp auth so, for the first time it will show after 30 sec if u click resend then otp will come and app was logged in
